<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="MPDTable.aspx.cs" Inherits="Test2.MPDTable" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

     <%--This panel is used to only show the page to authorized users (based on their role as defined in the Users table in DB)--%>
    <asp:Panel ID="authorizationPanel" runat="server">
        <div class="row mt-5">
            <div class="col">
                <h4>Edit/Delete</h4>
            </div>
        </div>

        <%--Dropdown list and search bar--%>
        <div class="row mt-4">
            <div class="col" style="position:relative;">
                <asp:DropDownList ID="tableList" runat="server" OnSelectedIndexChanged="tableList_SelectedIndexChanged" AutoPostBack="true" style="display:inline; position:absolute; top:0px; left: 15px;" Height="27px"></asp:DropDownList>
                <asp:Panel ID="searchPanel" runat="server">
                    <asp:TextBox ID="searchBox" runat="server" OnTextChanged="searchBox_TextChanged" AutoPostBack="true" style="display:inline; position:relative; left:125px; height:27px;"></asp:TextBox>
                    <asp:ImageButton ID="searchIcon" runat="server" ImageUrl="images/baseline_search_black_18dp.png" OnClick="searchIcon_Click" style="display:inline; position:relative; top:0px; left:125px"/>
                </asp:Panel>
            </div>
        </div>

        <%--GridView Data table--%>
        <div class="row mt-4">
            <div class="col">
                <asp:GridView ID="GridView1" runat="server" OnRowDeleting="GridView1_RowDeleting" 
                    AutoGenerateDeleteButton="true" 
                    AutoGenerateEditButton="True" 
                    EnableViewState="false" 
                    GridLines="None"
                    style="margin-bottom:25px;"
                    CellPadding="10" 
                    AutoGenerateColumns="False" 
                    AllowPaging="True"  
                    PageSize="5" 
                    OnPageIndexChanging="GridView1_PageIndexChanging"
                    OnRowEditing="GridView1_RowEditing" 
                    OnRowUpdating="GridView1_RowUpdating" 
                    OnRowCancelingEdit="GridView1_RowCancelingEdit"  
                    ></asp:GridView>
            </div>
        </div>

        <%--Modal for confirming delete which includes: ScriptManager, hiddenButton for use in TargetControlID attribute in ScriptManager and the Modal itself as a Panel--%>
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <ajaxToolkit:ModalPopupExtender ID="ModalExtender" runat="server" 
         PopupControlID="ModalPanel" OkControlID="deleteButton" CancelControlID="cancelButton" TargetControlID="hiddenButton"  />

        <asp:Button ID="hiddenButton" runat="server" Text="Button" style="display:none"/>

        <asp:Panel ID="ModalPanel" runat="server" BorderStyle="Solid" BorderWidth="1"
            style="
            background-color: #FFFFFF;
            border: 3px solid #CCC;
            padding-top: 10px;
            padding-left: 10px;
            width: 200px;
            height: 100px;
            clear: both;
            position: absolute;
            margin-top: 0;           
            text-align: center;
            z-index: 1;
            "         
        >
            Delete this record? <br />
            <asp:Button ID="deleteButton" runat="server" Text="Delete" OnClick="deleteButton_Click" UseSubmitBehavior="false" data-dismiss="modal" style="margin: 10px 15px 0px 0px"/>
            <asp:Button ID="cancelButton" runat="server" Text="Cancel" OnClick="cancelButton_Click" UseSubmitBehavior="false" data-dismiss="modal"/>
        </asp:Panel>

    </asp:Panel>

    <%--This panel is used to show errors or info about actions--%>
    <asp:Panel ID="statusPanel" runat="server"></asp:Panel>
</asp:Content>
